#!/bin/sh
#
# Launch syncthing from the installed snap.
#
# Arguments:
#   It passes the arguments it receives to the syncthing binary.
#   See the available arguments with syncthing -help.
#   If the -home argument is not passed, $SNAP_USER_COMMON is used, which is
#   expanded to $HOME/snap/syncthing/common.

if [[ "$@" =~ .-home.* ]]; then
  syncthing "$@"
else
  syncthing -home $SNAP_USER_COMMON "$@"
fi
